# Generated by Django 5.0.2 on 2024-08-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_delete_student'),
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registered_modules',
            field=models.ManyToManyField(blank=True, related_name='registered_students', to='courses.module'),
        ),
    ]
