# Generated by Django 5.0.2 on 2024-09-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Enter Module', max_length=255)),
                ('code', models.CharField(default=0, max_length=10)),
                ('credit', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('CORE', 'Core'), ('ELECTIVE', 'Elective'), ('OPTIONAL', 'Optional')], default='CORE', max_length=20)),
                ('description', models.TextField(default=' description')),
                ('availability', models.CharField(choices=[('OPEN', ' open for registration'), ('CLOSED', 'Closed')], default='CLOSED', max_length=10)),
                ('courses_allowed', models.ManyToManyField(blank=True, related_name='modules', to='courses.course')),
            ],
        ),
    ]
