# Generated by Django 5.0.2 on 2024-08-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0002_inquiry_remove_message_author_delete_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
